---
version: '2'

networks:
  monitoring:
    driver: bridge
  mynetwork:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local
  mypgdata:

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ismail1809!
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    volumes:
      - mypgdata:/var/lib/postgresql/data
    ports:
      - "5959:5432"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
      - prometheus-data:/prometheus
    links:
      - alertmanager:alertmanager
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '4000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - monitoring
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - alertmanager-data:/data
      - ./config/alertmanager-templates:/etc/alertmanager/alertmanager-templates
    command: --config.file=/etc/alertmanager/alertmanager.yml 
    networks:
      - monitoring

